# Generated by Django 3.2.16 on 2023-02-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230212_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='votanteprofile',
            name='votante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.votante'),
        ),
        migrations.CreateModel(
            name='VotanteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1024, null=True, verbose_name='message')),
                ('votante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.votante')),
            ],
        ),
    ]
