# Generated by Django 3.2.16 on 2023-02-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230212_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votante',
            old_name='codigo',
            new_name='document_id',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='nombre del departamento'),
        ),
    ]
