# Generated by Django 3.2.16 on 2023-02-13 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230212_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='custom_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
        ),
    ]
