# Generated by Django 3.2.16 on 2023-02-13 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_votante_custom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.municipio'),
        ),
    ]
