# Generated by Django 3.2.16 on 2023-02-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_votante_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puestovotacion',
            name='barrio',
        ),
        migrations.AlterField(
            model_name='puestovotacion',
            name='latitude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='puestovotacion',
            name='longitude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='longitude'),
        ),
    ]
