# Generated by Django 3.2.16 on 2023-02-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20230218_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votanteprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votanteprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER')], max_length=10, null=True),
        ),
    ]
