# Generated by Django 3.2.16 on 2023-04-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20230423_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.votante'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='custom_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser', verbose_name='supervisor'),
        ),
    ]
