# Generated by Django 3.2.16 on 2023-07-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20230424_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
