# Generated by Django 3.2.16 on 2023-08-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20230424_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='votanteprofile',
            name='latitude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='votanteprofile',
            name='longitude',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='longitude'),
        ),
    ]
