# Generated by Django 3.2.16 on 2023-08-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20230806_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='nombre de la campaña')),
                ('url', models.CharField(max_length=1024, verbose_name='sub url de la campaña')),
                ('is_active', models.BooleanField(default=True)),
                ('color_principal', models.CharField(max_length=10, verbose_name='principal_color')),
                ('color_secondary', models.CharField(max_length=10, verbose_name='principal_color')),
                ('longitude_principal', models.CharField(blank=True, max_length=1024, null=True, verbose_name='longitude')),
                ('latitude_principal', models.CharField(blank=True, max_length=1024, null=True, verbose_name='latitude')),
            ],
        ),
    ]
