# Generated by Django 3.2.16 on 2023-08-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='municipios',
            field=models.ManyToManyField(to='myapp.Municipio'),
        ),
    ]
