# Generated by Django 3.2.16 on 2023-08-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_campaign_municipios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votanteprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER'), ('Otro', 'Otro')], max_length=10, null=True),
        ),
    ]
