# Generated by Django 3.2.16 on 2023-08-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_votanteprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votanteprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO'), ('OTRO', 'OTRO')], max_length=10, null=True),
        ),
    ]
