# Generated by Django 3.2.16 on 2023-10-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_votanteprofile_validation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
