# Generated by Django 3.2.16 on 2024-10-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20230824_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votante',
            name='coordinador',
        ),
        migrations.AddField(
            model_name='votante',
            name='num_referidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votante',
            name='type',
            field=models.CharField(choices=[('VOTANTE', 'VOTANTE'), ('LIDER', 'LIDER'), ('DINAMIZADOR', 'DINAMIZADOR')], default='VOTANTE', max_length=12),
        ),
    ]
