# Generated by Django 5.2.3 on 2025-07-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_comuna_barrio_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='numero',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
