# Generated by Django 5.2.3 on 2025-07-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_comuna_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='numero',
            new_name='number',
        ),
    ]
